[package]
name = "ben"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
clap = {
    version = "4.6.7",
    default-features = false,
    features = ["derive", "error-context", "help", "std", "usage"],
}
crossterm = { version = "0.29.0", default-features = false, features = ["events"] }
futures-util = { version = "0.3.34", default-features = false, features = ["std"] }
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm"] }
reqwest = {
    version = "0.13.5",
    default-features = false,
    features = ["json", "rustls", "stream"],
}
serde = {
    version = "1.0.229",
    default-features = false,
    features = ["derive", "std"],
}
serde_json = { version = "1.0.151", default-features = false, features = ["std"] }
thiserror = "2.0.21"
tokio = {
    version = "1.53.2",
    default-features = false,
    features = ["io-util", "macros", "process", "rt-multi-thread", "sync", "time"],
}
tokio-util = { version = "0.7.19", default-features = false, features = ["rt"] }
tracing = {
    version = "0.1.44",
    default-features = false,
    features = ["attributes", "std"],
}
tracing-subscriber = {
    version = "0.3.23",
    default-features = false,
    features = ["env-filter", "fmt", "std"],
}

[dev-dependencies]
tempfile = { version = "3.27.0", default-features = false, features = ["getrandom"] }

[[bin]]
name = "ben"
path = "src/main.rs"
